# -*- coding: utf-8 -*-
"""Career_Aspiration_Survey_Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l1ab_EgPwfYNPhJbZPRIc3Pv3FCgxCif
"""

import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go

data = pd.read_csv('/content/Your Career Aspirations of GenZ.csv')

data.head()

data.info()

"""Total participants of the survey form by country."""

country = data['Your Current Country.'].value_counts()
label = country.index
counts = country.values
colors = ['lightred',['lightgreen']]

fig = go.Figure(data=[go.Pie(labels=label,values=counts)])
fig.update_layout(title_text="Total participants of the survey form by country")
fig.update_traces(hoverinfo="label+percent",textinfo="value",textfont_size=30,
                  marker=dict(colors=colors,line=dict(color='black',width=3)))
fig.show()

"""What is the Higher factors influence the most about your career aspirations ?"""

question1 = data[ 'Which of the below factors influence the most about your career aspirations ?'].value_counts()
label = question1.index
counts = question1.values
colors = ['yellow','blue']

fig = go.Figure(data=[go.Pie(labels=label,values=counts)])
fig.update_layout(title_text='Higher factors influence the most about your career aspirations')
fig.update_traces(hoverinfo='label+value',textinfo='percent',textfont_size=30,
                  marker=dict(colors=colors,line=dict(color='red',width=3)))
fig.show()

"""How many want to purse higher eduction outside india with there investment"""

question2 = data['Would you definitely pursue a Higher Education / Post Graduation outside of India ? If only you have to self sponsor it.'].value_counts()
label = question2.index
counts = question2.values
colors = ['purpule','pink']

fig = go.Figure(data=[go.Bar(x=label,y=counts)])
fig.update_layout(title_text='How many want to purse higher eduction outside india with there investment')
fig.show()

"""Total Survey participants by their Gender

"""

question3 = data['Your Gender'].value_counts()
label = question3.index
counts = question3.values
colors = ['red','blue']

fig = go.Figure(data=[go.Pie(labels=label,values=counts)])
fig.update_layout(title_text='Participants by their Gender')
fig.update_traces(hoverinfo='label',textinfo='value+percent',textfont_size=30,
                  marker=dict(colors=colors,line=dict(color='red',width=3)))
fig.show()

"""How likly Genz is to work for one company for three years or more ?"""

question4 = data['How likely is that you will work for one employer for 3 years or more ?'].value_counts()
labels = question4.index
counts = question4.values
colors=['red','blue','yellow']

fig = go.Figure(data=[go.Pie(labels=labels,values=counts)])
fig.update_layout(title_text='Working in same compay for three years')
fig.update_traces(hoverinfo='label',textinfo='value+percent',textfont_size=30,
                  marker=dict(colors=colors,line=dict(color='black',width=3)))

"""What is prefered working enviroment of Genz"""

question5 =  data['What is the most preferred working environment for you.'].value_counts()
label = question5.index
counts = question5.values
colors=['blue','green']

fig = go.Figure(data=[go.Pie(labels=label,values=counts)])
fig.update_layout(title_text='Prefered working enviroment of Genz')
fig.update_traces(hoverinfo='label',textinfo='value+percent',textfont_size=30,
                  marker=dict(colors=colors,line=dict(color='black',width=3)))

"""What kind of employer does nature prefer to work with?"""

question6 = data["Which of the below Employers would you work with."].value_counts()
label = question6.index
counts = question6.values
colors = ['gold','lightgreen']
fig = go.Figure(data=[go.Pie(labels=label, values=counts)])
fig.update_layout(title_text='Which of the below Employers would you work with?')
fig.update_traces(hoverinfo='label+value', textinfo='percent', textfont_size=30,
                  marker=dict(colors=colors, line=dict(color='black', width=3)))
fig.show()







